-- Automatic member activity and re-engagement workflow.
-- Run after schema_auth_rls.sql and schema_real_tables.sql.

alter table public.members add column if not exists inactive_since timestamptz;

create table if not exists public.member_reengagement_queue (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  member_id text not null,
  absence_started_at timestamptz not null,
  email text not null,
  status text not null default 'pending' check (status in ('pending', 'sent', 'failed')),
  sent_at timestamptz,
  error text,
  created_at timestamptz not null default now(),
  unique (owner_id, member_id, absence_started_at)
);

create index if not exists idx_member_reengagement_queue_pending
  on public.member_reengagement_queue (status, created_at);

alter table public.member_reengagement_queue enable row level security;
drop policy if exists "member_reengagement_queue_none" on public.member_reengagement_queue;
create policy "member_reengagement_queue_none"
on public.member_reengagement_queue for all
to authenticated
using (false)
with check (false);

create or replace function public.get_member_reengagement_status()
returns table (
  member_id text,
  email text,
  status text,
  absence_started_at timestamptz,
  sent_at timestamptz,
  error text,
  created_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select queue.member_id, queue.email, queue.status,
         queue.absence_started_at, queue.sent_at, queue.error, queue.created_at
  from public.member_reengagement_queue queue
  where queue.owner_id = auth.uid()
  order by queue.created_at desc;
$$;

revoke all on function public.get_member_reengagement_status() from public;
grant execute on function public.get_member_reengagement_status() to authenticated;

create or replace function public.refresh_member_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  member_row public.members%rowtype;
  has_consecutive_weeks boolean;
begin
  if new.member_id is null then
    return new;
  end if;

  select * into member_row
  from public.members
  where owner_id = new.owner_id and id = new.member_id;

  if not found or member_row.status <> 'Inactive' then
    return new;
  end if;

  with weekly_attendance as (
    select distinct date_trunc('week', coalesce(events.date::timestamptz, attendance.timestamp)) as attendance_week
    from public.attendance
    left join public.events
      on events.owner_id = attendance.owner_id and events.id = attendance.event_id
    where attendance.owner_id = new.owner_id
      and attendance.member_id = new.member_id
      and attendance.timestamp > coalesce(member_row.inactive_since, '-infinity'::timestamptz)
  )
  select exists (
    select 1
    from weekly_attendance first_week
    join weekly_attendance second_week
      on second_week.attendance_week = first_week.attendance_week + interval '7 days'
  ) into has_consecutive_weeks;

  if has_consecutive_weeks then
    update public.members
    set status = 'Active', inactive_since = null
    where owner_id = new.owner_id and id = new.member_id;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_attendance_refresh_member_activity on public.attendance;
create trigger trg_attendance_refresh_member_activity
after insert or update of member_id, event_id, timestamp on public.attendance
for each row
execute function public.refresh_member_activity();

create or replace function public.mark_members_inactive()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  member_row record;
  last_attendance timestamptz;
  absence_started_at timestamptz;
  changed_count integer := 0;
begin
  for member_row in
    select m.*
    from public.members m
    where m.archived = false and m.status = 'Active'
  loop
    select max(a.timestamp) into last_attendance
    from public.attendance a
    where a.owner_id = member_row.owner_id and a.member_id = member_row.id;

    absence_started_at := coalesce(
      last_attendance,
      case
        when member_row.joined ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
        then member_row.joined::date::timestamptz
        else null
      end,
      member_row.created_at
    );

    if absence_started_at <= now() - interval '1 month' and nullif(trim(member_row.email), '') is not null then
      insert into public.member_reengagement_queue (owner_id, member_id, absence_started_at, email)
      values (member_row.owner_id, member_row.id, absence_started_at, trim(member_row.email))
      on conflict (owner_id, member_id, absence_started_at) do nothing;
    end if;

    if absence_started_at <= now() - interval '2 months' then
      update public.members
      set status = 'Inactive', inactive_since = coalesce(inactive_since, absence_started_at)
      where owner_id = member_row.owner_id and id = member_row.id and status = 'Active';
      changed_count := changed_count + 1;
    end if;
  end loop;

  return changed_count;
end;
$$;

-- Schedule the member-reengagement Edge Function daily in Supabase Cron or an
-- external scheduler. The function calls mark_members_inactive before sending.