import { useMemo, useState } from "react";
import { Icon } from "./Icon.jsx";
import Avatar from "./Avatar.jsx";
import { getQRDataUrl } from "../utils/qr.js";


// ─── REPORTS VIEW ─────────────────────────────────────────────────────────────
function ReportsView({ attendance, members, events, theme, showNotif }) {
  const [eventSearch, setEventSearch] = useState("");
  const [selectedEvent, setSelectedEvent] = useState(events[0]?.id || "");
  const filteredEvents = useMemo(() => {
    const q = eventSearch.trim().toLowerCase();
    if (!q) return events;
    return events.filter((e) => {
      const label = `${e.name || ""} ${e.type || ""} ${e.date || ""} ${e.time || ""}`.toLowerCase();
      return label.includes(q) || String(e.id || "").toLowerCase().includes(q);
    });
  }, [eventSearch, events]);

  const eventData = attendance.filter(a => a.eventId === selectedEvent);
  const event = events.find(e => e.id === selectedEvent);

  const exportCSV = () => {
    if (!event) return;
    const rows = eventData.map(a => {
      const m = members.find(x => x.id === a.memberId);
      return `${a.memberId},"${a.memberName}","${event.name}",${new Date(a.timestamp).toLocaleDateString()},${new Date(a.timestamp).toLocaleTimeString()},${m?.ministry || ""}`;
    });
    const blob = new Blob([`Member ID,Name,Event,Date,Time,Ministry\n${rows.join("\n")}`], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a"); link.href = url; link.download = `TLOB_${event.name.replace(/\s+/g, "_")}.csv`; link.click();
    showNotif("CSV exported!");
  };

  const exportPDF = async () => {
    if (!event) return;
    const dataUrl = await getQRDataUrl(`TLOB-EVENT:${event.id}`, { width: 21 * 3, margin: 0, color: { dark: "#6366f1", light: "#ffffff" } });
    const qrImg = `<img src="${dataUrl}" width="${21*3}" height="${21*3}"/>`;
    const win = window.open("", "_blank");
    win.document.write(`<!DOCTYPE html><html><head><title>TLOB Report</title>
    <style>body{font-family:'Segoe UI',sans-serif;max-width:820px;margin:36px auto;color:#1a1a2e;}
    .header{display:flex;align-items:center;gap:20px;border-bottom:3px solid #6366f1;padding-bottom:20px;margin-bottom:24px;}
    .logo{width:52px;height:52px;background:linear-gradient(135deg,#6366f1,#06b6d4);border-radius:13px;display:flex;align-items:center;justify-content:center;color:white;font-size:24px;flex-shrink:0;}
    h1{font-size:22px;margin:0;}h2{font-size:14px;color:#6366f1;margin:3px 0 0;font-weight:400;}
    .meta{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:24px;}
    .mc{background:#f1f5f9;border-radius:10px;padding:13px;text-align:center;}
    .mc .v{font-size:24px;font-weight:700;color:#6366f1;}.mc .l{font-size:11px;color:#64748b;margin-top:2px;}
    table{width:100%;border-collapse:collapse;}
    th{background:#6366f1;color:white;padding:9px 13px;text-align:left;font-size:12px;}
    td{padding:9px 13px;border-bottom:1px solid #e2e8f0;font-size:13px;}
    tr:nth-child(even) td{background:#f8fafc;}
    .badge{display:inline-block;background:rgba(16,185,129,.15);color:#059669;padding:2px 9px;border-radius:999px;font-size:11px;font-weight:600;}
    .footer{margin-top:28px;text-align:center;font-size:11px;color:#94a3b8;border-top:1px solid #e2e8f0;padding-top:14px;}
    @media print{.footer{position:fixed;bottom:0;width:100%;}}</style></head><body>
    <div class="header"><div class="logo">⛪</div><div><h1>TLOB Church — Attendance Report</h1><h2>${event.name}</h2></div><div style="margin-left:auto">${qrImg}</div></div>
    <div class="meta">
      <div class="mc"><div class="v">${eventData.length}</div><div class="l">Attendees</div></div>
      <div class="mc"><div class="v">${event.date}</div><div class="l">Date</div></div>
      <div class="mc"><div class="v">${event.time}</div><div class="l">Time</div></div>
      <div class="mc"><div class="v">${event.type}</div><div class="l">Type</div></div>
    </div>
    <table><thead><tr><th>#</th><th>Member ID</th><th>Full Name</th><th>Ministry</th><th>Check-in</th><th>Status</th></tr></thead><tbody>
    ${eventData.map((a, i) => { const m = members.find(x => x.id === a.memberId); return `<tr><td>${i + 1}</td><td style="font-family:monospace;font-size:12px">${a.memberId}</td><td><strong>${a.memberName}</strong></td><td>${m?.ministry || "—"}</td><td>${new Date(a.timestamp).toLocaleTimeString()}</td><td><span class="badge">Present</span></td></tr>`; }).join("")}
    </tbody></table>
    <div class="footer">Generated by TLOB Attendance Management System • ${new Date().toLocaleString()}</div>
    </body></html>`);
    win.document.close();
    setTimeout(() => win.print(), 400);
    showNotif("PDF ready!");
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 18 }}>
      <div className="card" style={{ background: theme.surface, border: `1px solid ${theme.border}`, borderRadius: 13, padding: 22 }}>
        <div style={{ fontWeight: 600, fontSize: 14, marginBottom: 16 }}>Generate Report</div>
        <div style={{ display: "flex", gap: 10, alignItems: "flex-end", flexWrap: "wrap" }}>
          <div style={{ flex: 1, minWidth: 220 }}>
            <label>Select Event</label>
            <input
              type="text"
              placeholder="Search event..."
              value={eventSearch}
              onChange={(e) => setEventSearch(e.target.value)}
              style={{ marginBottom: 8 }}
            />
            <select value={selectedEvent} onChange={e => setSelectedEvent(e.target.value)}>
              {filteredEvents.map(e => <option key={e.id} value={e.id}>{e.name} ({e.date})</option>)}
            </select>
            {eventSearch.trim() && (
              <div style={{ fontSize: 11, color: theme.textMuted, marginTop: 6 }}>
                Showing {filteredEvents.length} of {events.length}
              </div>
            )}
          </div>
          <div style={{ display: "flex", gap: 9 }}>
            <button className="btn" onClick={exportCSV} style={{ background: `${theme.success}15`, color: theme.success, padding: "8px 16px", borderRadius: 8, fontSize: 13, fontWeight: 500, display: "flex", alignItems: "center", gap: 6 }}>
              <Icon name="download" size={15} /> Export CSV
            </button>
            <button className="btn" onClick={exportPDF} style={{ background: theme.accent, color: "white", padding: "8px 16px", borderRadius: 8, fontSize: 13, fontWeight: 500, display: "flex", alignItems: "center", gap: 6 }}>
              <Icon name="print" size={15} /> Print / PDF
            </button>
          </div>
        </div>
      </div>

      {event && (
        <div className="card" style={{ background: theme.surface, border: `1px solid ${theme.border}`, borderRadius: 13, overflow: "hidden" }}>
          <div style={{ padding: "18px 22px", borderBottom: `1px solid ${theme.border}`, display: "flex", justifyContent: "space-between", alignItems: "center", background: `linear-gradient(135deg,${theme.accent}0d,${theme.accent2}08)` }}>
            <div>
              <div style={{ fontWeight: 700, fontSize: 16 }}>TLOB Church — Attendance Report</div>
              <div style={{ fontSize: 12, color: theme.textMuted, marginTop: 3 }}>{event.name} • {event.date} at {event.time}</div>
            </div>
            <div style={{ textAlign: "center" }}>
              <div style={{ fontSize: 30, fontWeight: 700, color: theme.accent }}>{eventData.length}</div>
              <div style={{ fontSize: 10, color: theme.textMuted }}>Attendees</div>
            </div>
          </div>
          <table>
            <thead><tr><th>#</th><th>Member ID</th><th>Full Name</th><th>Ministry</th><th>Check-in</th><th>Status</th></tr></thead>
            <tbody>
              {eventData.map((a, i) => {
                const m = members.find(x => x.id === a.memberId);
                return (
                  <tr key={a.id}>
                    <td style={{ color: theme.textMuted, fontSize: 11 }}>{i + 1}</td>
                    <td><code style={{ background: theme.surface2, padding: "2px 6px", borderRadius: 4, fontSize: 11 }}>{a.memberId}</code></td>
                    <td>
                      <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                        <Avatar member={m || { name: a.memberName }} size={24} />
                        <span style={{ fontWeight: 500, fontSize: 13 }}>{a.memberName}</span>
                      </div>
                    </td>
                    <td style={{ color: theme.textMuted, fontSize: 12 }}>{m?.ministry || "—"}</td>
                    <td style={{ fontSize: 12 }}><span style={{ background: `${theme.success}12`, color: theme.success, borderRadius: 5, padding: "2px 7px" }}>{new Date(a.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</span></td>
                    <td><span className="badge tag-active">Present</span></td>
                  </tr>
                );
              })}
            </tbody>
          </table>
          {eventData.length === 0 && <div style={{ padding: 36, textAlign: "center", color: theme.textMuted }}>No records for this event</div>}
        </div>
      )}
    </div>
  );
}

export default ReportsView;
